FROM node:20

# Tạo thư mục làm việc
WORKDIR /app

# Copy package files và cài đặt dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .
COPY tsconfig.json ./

# Mở port container
EXPOSE 9000

# Chạy service
CMD ["npm", "run", "dev"]